#!/usr/bash/env
#I use curl to query web-01.holberton.online, and since my firewall is forwarding the ports, I get a HTTP 200 response on port 80/TCP and also on port 8080/TCP.
sudo nano /etc/nginx/sites-enabled/default
sudo systemctl restart nginx
curl -sI web-01.holberton.online:80
curl -sI web-01.holberton.online:8080
